--- 
title: "Solving Statistical Problems"
author: "Salvador Balkus, Kimberly Greco, and Mónica Robles Fontán"
  
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: salbalkus/Solving-Statistical-Problems
description: "Solving Statistical Problems"
---

# Introduction

Welcome to "Solving Statistical Problems", a compilation of problem-solving tools and tricks for graduate-level Probability and Statistical Inference courses. This site is currently under construction in preparation for the 2023 Harvard Biostatistics PhD Qualifying Exam. 

Many of our examples originate from or are inspired by Casella and Berger's *Statistical Inference*, [The Book of Statistical Proofs](https://statproofbook.github.io/), lectures slides and notes from *BIOSTAT 230: Probability I* and *BIOSTAT 231: Statistical Inference I* at the Harvard Department of Biostatistics, and other online resources. The authors' hope is that students in the aforementioned courses (and similar courses at other universities) can use this book as a supplement to aid in their understanding of graduate-level statistics material.
